#!/bin/bash
# PUSH WITH TOKEN

echo "🔑 GITHUB TOKEN PUSH"
echo ""
echo "======================================"
echo "FIRST: CREATE TOKEN"
echo "======================================"
echo ""
echo "Go to: https://github.com/settings/tokens/new"
echo ""
echo "Settings:"
echo "  Name: Backend Deploy"
echo "  Expiration: 90 days"
echo "  Scopes: ✅ repo (check the main box)"
echo ""
echo "Click 'Generate token' and COPY IT!"
echo ""
echo "======================================"
echo "THEN: RUN THIS COMMAND"
echo "======================================"
echo ""
echo "cd \"/Users/admin/Downloads/KÕIGE UUEM/BACKEND\""
echo "git push https://YOUR_TOKEN@github.com/Zaza4real/lypo-backend.git main"
echo ""
echo "Replace YOUR_TOKEN with your actual token!"
echo ""
echo "Example:"
echo "git push https://ghp_abc123xyz@github.com/Zaza4real/lypo-backend.git main"
echo ""
echo "======================================"
echo ""
